allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

def repoBuildDir = rootProject.file("../build")
rootProject.buildDir = repoBuildDir

subprojects { project ->
    if (project.projectDir.toPath().startsWith(rootDir.toPath())) {
        project.buildDir = new File(repoBuildDir, project.name)
    }
}
subprojects {
    project.evaluationDependsOn(":app")
}

tasks.register("clean", Delete) {
    delete repoBuildDir
}
